modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Adam Young"
description="Advanced pneumatic logistics for ProjectRed, inspired by RedPower 2."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="projectred_core"
type="required"
versionRange="[4.23.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="projectred_expansion"
type="required"
versionRange="[4.23.0,)"
ordering="AFTER"
side="BOTH"
